linters:
  enable:
    - revive
    - gofmt
    - testifylint
    - stylecheck
    - predeclared
    - makezero
    - tenv
    - copyloopvar
    - protogetter
    - nonamedreturns
run:
  timeout: 30m0s
