linters:
  enable:
    - revive
    - gofmt
    - gofumpt
    - testifylint
    - stylecheck
    - predeclared
    - makezero
    - tenv
    - copyloopvar
    - protogetter
    - nonamedreturns
    - gci
    - forbidigo
run:
  timeout: 30m0s
