---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # You can change the name to identify this PVC
  name: pvc-lustre
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      # This size must be the true size of the Azure Managed Lustre you want
      # to used. Or the volume create process may fail.
      storage: 4Ti
  # This field must be the same as the name in StorageClass
  storageClassName: sc.amlfs.csi.azure.com
