---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # The name of the PVC
  name: pvc-lustre
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  # This field must be the same as PV name in PersistentVolume.
  volumeName: pv-lustre
  storageClassName: ""
