---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # You can change the name to identify this PVC
  name: pvc-lustre
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: sc.amlfs.csi.azure.com
