apiVersion: v1
kind: Pod
metadata:
  name: msft-laaso-lustre-app2a
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo \"For BrianB... $(cat /lustre/imported_file1.txt)\"; sleep 10; done"]
    volumeMounts:
    - name: lustre-mount
      mountPath: /lustre
  volumes:
  - name: lustre-mount
    persistentVolumeClaim:
      claimName: msft-laaso-lustre-claim1
