apiVersion: v1
kind: Pod
metadata:
  name: msft-laaso-lustre-demo-app1
spec:
  containers:
  - name: demo-container
    image: jgalaasocr.azurecr.io/laaso/csi-demo-pod:latest
    volumeMounts:
    - name: lustre-mount
      mountPath: /lustre
  volumes:
  - name: lustre-mount
    persistentVolumeClaim:
      claimName: msft-laaso-lustre-claim1
