---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sc.azurelustre.csi.azure.com
provisioner: azurelustre.csi.azure.com
parameters:
  mgs-ip-address: "172.17.0.7"      # 1st azurelustre cluster for daily work, dev1
  #mgs-ip-address: "172.16.0.4"     # 2nd azurelustre cluster for long-haul and PR gated check-in
  fs-name: "lustrefs"
