---

kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: msft-laaso-lustre-csi-node
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: msft-laaso-lustre-csi-node
  template:
    metadata:
      labels:
        app: msft-laaso-lustre-csi-node
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
      hostNetwork: true
      containers:
        - name: msft-laaso-node-plugin
          securityContext:
            privileged: true
          image: jusjin.azurecr.io/msft-laaso-lustre-csi:latest
          args:
            - --endpoint=$(CSI_ENDPOINT)
          env:
            - name: CSI_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: laaso-csi-config
                  key: csi-endpoint
          volumeMounts:
            - name: kubelet-dir
              mountPath: /var/lib/kubelet
              mountPropagation: "Bidirectional"
            - name: socket-dir
              mountPath: /csi
            - name: lustre-mount
              mountPath: /var/lib/kubelet/pods
              mountPropagation: "Bidirectional"
          ports:
            - containerPort: 9810
              name: healthz
              protocol: TCP
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 120
            timeoutSeconds: 3
            periodSeconds: 2
        - name: node-driver-registrar
          image: mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar:v2.0.1
          args:
            - --csi-address=$(ADDRESS)
            - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
            - --v=2
            - --health-port=9809
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: /var/lib/kubelet/plugins/msft.laaso.lustre.csi.com/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 20Mi
        - name: liveness-probe
          image: mcr.microsoft.com/oss/kubernetes-csi/livenessprobe:v2.2.0
          args:
            - --csi-address=/csi/csi.sock
            - --probe-timeout=3s
            - --health-port=9810
            - --v=2
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 20Mi
      volumes:
        - name: kubelet-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: Directory
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/msft.laaso.lustre.csi.com/
            type: DirectoryOrCreate
        - name: module-dir
          hostPath:
            path: /lib/modules
        - name: lustre-mount
          hostPath:
            path: /var/lib/kubelet/pods
