name: MacOS Build & Unit Test

# Controls when the workflow will run
#on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
    #branches: [ main ]
  #pull_request:
    #branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Build Test
        run: |
          make azurelustre-darwin
      - name: Run unit tests on MacOS
        run: go test -v -race ./pkg/...
