---
name: External E2E Test

on:
  workflow_dispatch:

jobs:
  Run-external-e2e-test:
    name: Run External E2E Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Run External E2E Test
        run: test/external-e2e/run.sh
