---
name: Long-Haul Test

# on:
#   schedule:
#     - cron: '0 0 */1 * *'

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Run-long-haul-on-AKS:
    name: Run long-haul on AKS
    runs-on: ubuntu-latest    
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        
      - name: Azure Login
        uses: Azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run test
        run: |
          ./test/long-haul/start-long-haul.sh
        env:
          aks_cluster_name: ${{ secrets.AKS_LONGHAUL_CLUSTER }}
          aks_resource_group: ${{ secrets.AKS_LONGHAUL_RG }}
          aks_pool_name: ${{ secrets.AKS_LONGHAUL_POOL }}
          lustre_fs_name: ${{ secrets.LUSTRE_FS_NAME }}
          lustre_fs_ip: ${{ secrets.LUSTRE_FS_IP }}
