name: Sanity Test Local

# Controls when the workflow will run
on:
  push: {}
  pull_request: {}
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Run-Sanity-Test-Local:
    name: Run Sanity Test Local
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
      id: go
    - name: Run Sanity Test
      run: make sanity-test-local
