name: Sanity Test Local

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Run-Sanity-Test-Local:
    name: Run Sanity Test Local
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Run Sanity Test
      run: make sanity-test-local
