name: Static Checks

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    go_lint:
        name: Go Lint
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/setup-go@v3
              with:
                go-version: 1.19
            - name: Checkout code
              uses: actions/checkout@master
            - name: Run linter
              uses: golangci/golangci-lint-action@v3
              with:
                  working-directory: pkg
                  args: -E=gofmt --timeout=30m0s
