name: Static Checks

# Controls when the workflow will run
on:
  pull_request: {}
  push: {}
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    go_lint:
        name: Go Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-go@v5
              with:
                go-version-file: 'go.mod'
            - name: Checkout code
              uses: actions/checkout@master
            - name: Run linter
              uses: golangci/golangci-lint-action@v6
              with:
                  working-directory: pkg
                  args: -E=gofmt --timeout=30m0s
